import React from 'react';
import {
  SunMedium,
  UtensilsCrossed,
  Sparkles,
  CheckSquare,
  Gamepad2,
  Soup,
  BookOpen,
  Bath,
  Backpack,
  Moon,
  Trees,
  Tv,
  BedDouble,
  Box,
  Shirt,
  Utensils,
  Smile,
  Droplets,
  Check,
  PenTool,
  GlassWater,
  Compass,
  Clock,
  Heart,
  Music,
  Activity,
  Footprints,
  Baby,
  Brush,
  Coffee,
  HelpCircle,
  Toilet,
  ShowerHead,
  Hand,
  SoapDispenserDroplet,
} from 'lucide-react';

interface TaskIconProps {
  name: string;
  className?: string;
  size?: number;
}

const ICON_MAP: Record<string, React.ComponentType<{ className?: string; size?: number }>> = {
  SunMedium,
  UtensilsCrossed,
  Sparkles,
  CheckSquare,
  Gamepad2,
  Soup,
  BookOpen,
  Bath,
  Backpack,
  Moon,
  Trees,
  Tv,
  BedDouble,
  Box,
  Shirt,
  Utensils,
  Smile,
  Droplets,
  Check,
  PenTool,
  GlassWater,
  Compass,
  Clock,
  Heart,
  Music,
  Activity,
  Footprints,
  Baby,
  Brush,
  Coffee,
  Toilet,
  ShowerHead,
  Hand,
  SoapDispenserDroplet,
};

export const AVAILABLE_ICONS = [
  { name: 'Toilet', label: 'Banheiro / Privada / Vaso' },
  { name: 'ShowerHead', label: 'Chuveiro / Banho' },
  { name: 'Hand', label: 'Lavar as Mãos' },
  { name: 'Sparkles', label: 'Higiene / Dentes' },
  { name: 'Bath', label: 'Banheira' },
  { name: 'CheckSquare', label: 'Tarefas / Lista' },
  { name: 'UtensilsCrossed', label: 'Alimentação / Café' },
  { name: 'Soup', label: 'Almoço / Jantar' },
  { name: 'SunMedium', label: 'Manhã / Despertar' },
  { name: 'Moon', label: 'Dormir / Noite' },
  { name: 'BookOpen', label: 'Escola / Leitura' },
  { name: 'Backpack', label: 'Mochila' },
  { name: 'Gamepad2', label: 'Brincar / Games' },
  { name: 'BedDouble', label: 'Arrumar Cama' },
  { name: 'Box', label: 'Guardar Brinquedos' },
  { name: 'Shirt', label: 'Roupa / Vestir' },
  { name: 'Trees', label: 'Passeio ao ar livre' },
  { name: 'Tv', label: 'Desenho / TV' },
  { name: 'PenTool', label: 'Desenhar / Lição' },
  { name: 'Heart', label: 'Terapia / Acolhimento' },
  { name: 'GlassWater', label: 'Beber Água' },
  { name: 'Music', label: 'Música' },
  { name: 'Activity', label: 'Exercício / Fisioterapia' },
];

export const TaskIcon: React.FC<TaskIconProps> = ({ name, className = 'w-6 h-6', size }) => {
  const IconComponent = ICON_MAP[name] || HelpCircle;
  return <IconComponent className={className} size={size} />;
};

export const COLOR_THEMES: Record<string, { bg: string; text: string; border: string; badge: string; softBg: string; ring: string }> = {
  amber: {
    bg: 'bg-amber-500',
    text: 'text-amber-700',
    border: 'border-amber-200',
    badge: 'bg-amber-100 text-amber-800',
    softBg: 'bg-amber-50',
    ring: 'focus:ring-amber-400',
  },
  emerald: {
    bg: 'bg-emerald-500',
    text: 'text-emerald-700',
    border: 'border-emerald-200',
    badge: 'bg-emerald-100 text-emerald-800',
    softBg: 'bg-emerald-50',
    ring: 'focus:ring-emerald-400',
  },
  cyan: {
    bg: 'bg-cyan-500',
    text: 'text-cyan-700',
    border: 'border-cyan-200',
    badge: 'bg-cyan-100 text-cyan-800',
    softBg: 'bg-cyan-50',
    ring: 'focus:ring-cyan-400',
  },
  indigo: {
    bg: 'bg-indigo-500',
    text: 'text-indigo-700',
    border: 'border-indigo-200',
    badge: 'bg-indigo-100 text-indigo-800',
    softBg: 'bg-indigo-50',
    ring: 'focus:ring-indigo-400',
  },
  violet: {
    bg: 'bg-violet-500',
    text: 'text-violet-700',
    border: 'border-violet-200',
    badge: 'bg-violet-100 text-violet-800',
    softBg: 'bg-violet-50',
    ring: 'focus:ring-violet-400',
  },
  blue: {
    bg: 'bg-blue-500',
    text: 'text-blue-700',
    border: 'border-blue-200',
    badge: 'bg-blue-100 text-blue-800',
    softBg: 'bg-blue-50',
    ring: 'focus:ring-blue-400',
  },
  teal: {
    bg: 'bg-teal-500',
    text: 'text-teal-700',
    border: 'border-teal-200',
    badge: 'bg-teal-100 text-teal-800',
    softBg: 'bg-teal-50',
    ring: 'focus:ring-teal-400',
  },
  rose: {
    bg: 'bg-rose-500',
    text: 'text-rose-700',
    border: 'border-rose-200',
    badge: 'bg-rose-100 text-rose-800',
    softBg: 'bg-rose-50',
    ring: 'focus:ring-rose-400',
  },
  sky: {
    bg: 'bg-sky-500',
    text: 'text-sky-700',
    border: 'border-sky-200',
    badge: 'bg-sky-100 text-sky-800',
    softBg: 'bg-sky-50',
    ring: 'focus:ring-sky-400',
  },
};
