import { RoutineTask, SubTask } from '../types';

export interface ClinicalRoutineTemplate {
  id: string;
  title: string;
  badge: string;
  description: string;
  categoryName: string;
  iconName: string;
  accentColor: string;
  tasks: Omit<RoutineTask, 'id' | 'completed' | 'completedAt'>[];
}

export const CLINICAL_TEMPLATES: ClinicalRoutineTemplate[] = [
  {
    id: 'template-desfralde',
    title: 'Treino de Desfralde & Toalete',
    badge: 'Autonomia & Higiene',
    description:
      'Passo a passo visual e sensorial completo para transição de fralda e ida ao banheiro sem medo.',
    categoryName: 'Higiene & Toalete',
    iconName: 'Toilet',
    accentColor: 'sky',
    tasks: [
      {
        title: 'Sentir a Vontade e Avisar',
        time: '08:00',
        category: 'hygiene',
        iconName: 'Smile',
        color: 'sky',
        soundAlert: 'chime',
        voicePhrase: 'Muito bem! Quando tiver vontade de fazer xixi ou cocô, vamos ao banheiro.',
        durationMinutes: 5,
        notes: 'Incentivar o paciente a apontar o cartão ou falar.',
        subtasks: [
          { id: 'st-d1', title: 'Perceber a vontade de xixi ou cocô', completed: false },
          { id: 'st-d2', title: 'Caminhar calmamente até o banheiro', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/5921/5921_300.png',
      },
      {
        title: 'Preparar a Roupa',
        time: '08:05',
        category: 'hygiene',
        iconName: 'Shirt',
        color: 'indigo',
        soundAlert: 'chime',
        voicePhrase: 'Abaixe o short e a calcinha ou cueca devagar.',
        durationMinutes: 3,
        subtasks: [
          { id: 'st-d3', title: 'Abaixar a bermuda/calça', completed: false },
          { id: 'st-d4', title: 'Abaixar a cueca ou calcinha', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/32464/32464_300.png',
      },
      {
        title: 'Sentar no Vaso Sanitário',
        time: '08:08',
        category: 'hygiene',
        iconName: 'Toilet',
        color: 'sky',
        soundAlert: 'marimba',
        voicePhrase: 'Sente-se com calma com os pezinhos apoiados.',
        durationMinutes: 7,
        notes: 'Uso de redutor de assento e apoio para os pés para dar segurança postural.',
        subtasks: [
          { id: 'st-d5', title: 'Apoiar os pezinhos no banquinho', completed: false },
          { id: 'st-d6', title: 'Relaxar a barriguinha e respirar fundo', completed: false },
          { id: 'st-d7', title: 'Fazer o xixi ou cocô no vaso', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/5921/5921_300.png',
      },
      {
        title: 'Limpar e Dar a Descarga',
        time: '08:15',
        category: 'hygiene',
        iconName: 'Droplets',
        color: 'cyan',
        soundAlert: 'bell',
        voicePhrase: 'Limpar com papel e dar tchau para o xixi apertando a descarga!',
        durationMinutes: 4,
        subtasks: [
          { id: 'st-d8', title: 'Usar o papel higiênico com cuidado', completed: false },
          { id: 'st-d9', title: 'Jogar o papel na lixeira', completed: false },
          { id: 'st-d10', title: 'Subir a roupa íntima e o short', completed: false },
          { id: 'st-d11', title: 'Apertar a descarga', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/6280/6280_300.png',
      },
      {
        title: 'Lavar e Secar as Mãos',
        time: '08:20',
        category: 'hygiene',
        iconName: 'Hand',
        color: 'emerald',
        soundAlert: 'harp',
        voicePhrase: 'Parabéns! Agora mãos limpinhas e cheirosas.',
        durationMinutes: 5,
        subtasks: [
          { id: 'st-d12', title: 'Molhar as mãos na torneira', completed: false },
          { id: 'st-d13', title: 'Passar sabonete e fazer bastante espuma', completed: false },
          { id: 'st-d14', title: 'Enxaguar toda a espuminha', completed: false },
          { id: 'st-d15', title: 'Secar bem na toalha', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/2445/2445_300.png',
      },
    ],
  },
  {
    id: 'template-matinal',
    title: 'Rotina Matinal Estruturada',
    badge: 'Início do Dia',
    description:
      'Transição suave do despertar até a saída para a escola ou terapias, diminuindo a ansiedade matinal.',
    categoryName: 'Rotina Diária',
    iconName: 'SunMedium',
    accentColor: 'amber',
    tasks: [
      {
        title: 'Acordar e Espreguiçar',
        time: '07:00',
        category: 'hygiene',
        iconName: 'SunMedium',
        color: 'amber',
        soundAlert: 'chime',
        voicePhrase: 'Bom dia! Hora de acordar com calma e respirar fundo.',
        durationMinutes: 10,
        subtasks: [
          { id: 'st-m1', title: 'Abrir os olhos devagar', completed: false },
          { id: 'st-m2', title: 'Espreguiçar braços e pernas', completed: false },
          { id: 'st-m3', title: 'Levantar da cama', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/6049/6049_300.png',
      },
      {
        title: 'Ir ao Banheiro e Lavar o Rosto',
        time: '07:15',
        category: 'hygiene',
        iconName: 'Toilet',
        color: 'sky',
        soundAlert: 'bell',
        voicePhrase: 'Xixi matinal e água fresca no rostinho.',
        durationMinutes: 10,
        subtasks: [
          { id: 'st-m4', title: 'Fazer xixi no vaso', completed: false },
          { id: 'st-m5', title: 'Lavar o rosto e mãos', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/5921/5921_300.png',
      },
      {
        title: 'Vestir a Roupa do Dia',
        time: '07:25',
        category: 'chores',
        iconName: 'Shirt',
        color: 'indigo',
        soundAlert: 'marimba',
        voicePhrase: 'Tirar o pijama e vestir a roupinha de hoje.',
        durationMinutes: 15,
        subtasks: [
          { id: 'st-m6', title: 'Tirar o pijama e colocar no cesto', completed: false },
          { id: 'st-m7', title: 'Vestir a camiseta e bermuda ou calça', completed: false },
          { id: 'st-m8', title: 'Colocar as meias', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/6879/6879_300.png',
      },
      {
        title: 'Café da Manhã Gostoso',
        time: '07:40',
        category: 'meals',
        iconName: 'UtensilsCrossed',
        color: 'emerald',
        soundAlert: 'harp',
        voicePhrase: 'Hora de comer com calma para ter bastante energia!',
        durationMinutes: 25,
        subtasks: [
          { id: 'st-m9', title: 'Sentar à mesa', completed: false },
          { id: 'st-m10', title: 'Comer a fruta e o pãozinho', completed: false },
          { id: 'st-m11', title: 'Beber leite ou suco', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/2381/2381_300.png',
      },
      {
        title: 'Escovar os Dentinhos',
        time: '08:05',
        category: 'hygiene',
        iconName: 'Sparkles',
        color: 'cyan',
        soundAlert: 'harp',
        voicePhrase: 'Vamos escovar os dentes para ficarem limpinhos e brilhantes!',
        durationMinutes: 5,
        subtasks: [
          { id: 'st-m12', title: 'Pasta na escova', completed: false },
          { id: 'st-m13', title: 'Escovar em cima, embaixo e atrás', completed: false },
          { id: 'st-m14', title: 'Enxaguar a boquinha', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/2443/2443_300.png',
      },
      {
        title: 'Conferir Mochila e Calçar Sapatos',
        time: '08:15',
        category: 'school',
        iconName: 'BookOpen',
        color: 'rose',
        soundAlert: 'bell',
        voicePhrase: 'Mochila pronta e sapatos calçados. Estamos prontos!',
        durationMinutes: 15,
        subtasks: [
          { id: 'st-m15', title: 'Conferir garrafinha e estojo', completed: false },
          { id: 'st-m16', title: 'Calçar o tênis', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/2573/2573_300.png',
      },
    ],
  },
  {
    id: 'template-noturno',
    title: 'Higiene & Preparo para o Sono',
    badge: 'Desaceleração Noturna',
    description:
      'Rotina com baixo estímulo sensorial para acalmar a mente e o corpo antes de dormir.',
    categoryName: 'Sono & Relaxamento',
    iconName: 'Moon',
    accentColor: 'indigo',
    tasks: [
      {
        title: 'Guardar Brinquedos e Desligar Telas',
        time: '19:30',
        category: 'chores',
        iconName: 'Box',
        color: 'indigo',
        soundAlert: 'chime',
        voicePhrase: 'Hora de desligar as telas e guardar os brinquedos na caixinha.',
        durationMinutes: 15,
        subtasks: [
          { id: 'st-n1', title: 'Desligar celular, tablet e TV', completed: false },
          { id: 'st-n2', title: 'Guardar os brinquedos', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/32462/32462_300.png',
      },
      {
        title: 'Banho Morno Relaxante',
        time: '19:50',
        category: 'hygiene',
        iconName: 'Bath',
        color: 'cyan',
        soundAlert: 'harp',
        voicePhrase: 'Água morninha e relaxante para descansar o corpo.',
        durationMinutes: 20,
        subtasks: [
          { id: 'st-n3', title: 'Entrar no banho morno', completed: false },
          { id: 'st-n4', title: 'Lavar o corpinho com sabonete', completed: false },
          { id: 'st-n5', title: 'Secar bem na toalha fofinha', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/2444/2444_300.png',
      },
      {
        title: 'Colocar o Pijama Confortável',
        time: '20:15',
        category: 'chores',
        iconName: 'Shirt',
        color: 'sky',
        soundAlert: 'bell',
        voicePhrase: 'Vestir o pijama quentinho.',
        durationMinutes: 10,
        subtasks: [
          { id: 'st-n6', title: 'Vestir a calça do pijama', completed: false },
          { id: 'st-n7', title: 'Vestir a blusa do pijama', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/6879/6879_300.png',
      },
      {
        title: 'Escovar os Dentes e Xixi da Noite',
        time: '20:25',
        category: 'hygiene',
        iconName: 'Sparkles',
        color: 'emerald',
        soundAlert: 'harp',
        voicePhrase: 'Dentes limpinhos e xixi antes da cama.',
        durationMinutes: 10,
        subtasks: [
          { id: 'st-n8', title: 'Escovar bem todos os dentes', completed: false },
          { id: 'st-n9', title: 'Fazer o último xixi da noite', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/2443/2443_300.png',
      },
      {
        title: 'História Calma e Dormir',
        time: '20:45',
        category: 'sleep',
        iconName: 'Moon',
        color: 'indigo',
        soundAlert: 'harp',
        voicePhrase: 'Boa noite! Hora de ouvir uma historinha e ter lindos sonhos.',
        durationMinutes: 25,
        subtasks: [
          { id: 'st-n10', title: 'Deitar na caminha macia', completed: false },
          { id: 'st-n11', title: 'Ouvir uma historinha ou música calma', completed: false },
          { id: 'st-n12', title: 'Fechar os olhinhos e dormir', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/2571/2571_300.png',
      },
    ],
  },
  {
    id: 'template-terapia',
    title: 'Sessão no Consultório Terapêutico',
    badge: 'Clínica & Terapia',
    description:
      'Estrutura previsível para sessões de Psicologia, Fonoaudiologia ou Terapia Ocupacional.',
    categoryName: 'Clínica & Consultório',
    iconName: 'Sparkles',
    accentColor: 'rose',
    tasks: [
      {
        title: 'Chegada e Acolhimento',
        time: '14:00',
        category: 'therapy',
        iconName: 'Smile',
        color: 'rose',
        soundAlert: 'bell',
        voicePhrase: 'Oi! Que bom ver você hoje na nossa sala.',
        durationMinutes: 5,
        subtasks: [
          { id: 'st-t1', title: 'Entrar na sala e cumprimentar a terapeuta', completed: false },
          { id: 'st-t2', title: 'Tirar sapatos ou mochila no cantinho', completed: false },
          { id: 'st-t3', title: 'Olhar a prancha da sessão de hoje', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/37191/37191_300.png',
      },
      {
        title: 'Atividade 1: Foco na Mesa',
        time: '14:05',
        category: 'therapy',
        iconName: 'CheckSquare',
        color: 'indigo',
        soundAlert: 'chime',
        voicePhrase: 'Primeiro fazemos nossa atividade na mesa com atenção.',
        durationMinutes: 15,
        subtasks: [
          { id: 'st-t4', title: 'Sentar na cadeira confortável', completed: false },
          { id: 'st-t5', title: 'Fazer o pareamento ou atividade cognitiva', completed: false },
          { id: 'st-t6', title: 'Guardar o material da mesa', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/6871/6871_300.png',
      },
      {
        title: 'Pausa de Movimento / Sensorial',
        time: '14:20',
        category: 'play',
        iconName: 'Gamepad2',
        color: 'amber',
        soundAlert: 'marimba',
        voicePhrase: 'Agora um momento para pular, relaxar ou respirar.',
        durationMinutes: 10,
        subtasks: [
          { id: 'st-t7', title: 'Circuito motor ou massinha sensorial', completed: false },
          { id: 'st-t8', title: 'Beber um golinho de água', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/2344/2344_300.png',
      },
      {
        title: 'Atividade 2: Jogo Social / Lúdico',
        time: '14:30',
        category: 'play',
        iconName: 'Sparkles',
        color: 'emerald',
        soundAlert: 'chime',
        voicePhrase: 'Hora de brincar e compartilhar!',
        durationMinutes: 15,
        subtasks: [
          { id: 'st-t9', title: 'Esperar a sua vez na brincadeira', completed: false },
          { id: 'st-t10', title: 'Comunicação e trocas sociais', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/2343/2343_300.png',
      },
      {
        title: 'Organizar e Despedida com Reforço Positivo',
        time: '14:45',
        category: 'therapy',
        iconName: 'Check',
        color: 'teal',
        soundAlert: 'harp',
        voicePhrase: 'Parabéns pelo excelente trabalho de hoje! Até a próxima sessão.',
        durationMinutes: 5,
        subtasks: [
          { id: 'st-t11', title: 'Guardar todos os materiais usados', completed: false },
          { id: 'st-t12', title: 'Ganhar carimbo, adesivo ou elogio', completed: false },
          { id: 'st-t13', title: 'Dar tchau para a terapeuta', completed: false },
        ],
        imageUrl: 'https://static.arasaac.org/pictograms/32462/32462_300.png',
      },
    ],
  },
];
